---
title: "HW_July_12"
author: "Rongkui Han"
date: "July 11, 2017"
output: 
  html_document: 
    keep_md: yes
---
###Strings  
####14.1.1 Prerequisites  
```{r}
library(tidyverse)
library(stringr)
```

###14.2 String basics  
```{r}
string1 = "This is a string"
string2 = 'If I want to include a "quote" inside a string, I use single quotes'
"This is a string without a closing quote
HELP I'M STUCK"
#press escape to escape. 
double_quote = "\""
double_quote
single_quote = '\''
single_quote
x = c("\"", "\\")
x
writeLines(x) #weird.
writeLines("\n") #new line
writeLines("\t") #tab
writeLines("\u00b5")
c("one","two","three")
```

####14.2.1 String length  
```{r}
str_length(c("a","R for data science", NA)) #space counts as length too
```

####14.2.2 Combining stings  

```{r}
str_c("x","y") #wow
str_c("x","y","z")
str_c("x","y", sep = ", ")
x = c("abc",NA)
str_c("|-",x,"-|")
str_c("|-",str_replace_na(x),"-|")
str_replace_na(x) #turns NA into literal "NA"
str_c("prefix-", c("a", "b", "c"), "-suffix")
```

```{r}
name = "Hadley"
time_of_day = "morning"
birthday = FALSE
str_c("Good ",time_of_day, " ", name, if (birthday) " and HAPPY BIRTHDAY", ".")
birthday2 = TRUE
str_c("Good ",time_of_day, " ", name, if (birthday2) " and HAPPY BIRTHDAY", ".")

str_c(c("x", "y", "z"), collapse = ",") #to collapse a vector into a single string. 
```

####14.2.3 Subsetting strings  
```{r}
x = c("Apple","Banana","Pear")
str_sub(x,1,3)
str_sub(x, -3, -1) #negative numbers count backwards from end
str_sub("a", 1, 5) #won't fail if string is too short
str_sub(x, 1, 1) = str_to_lower(str_sub(x,1,1))
x
#accidentally found this fun thing:
str_sub(x, 1, 1) = str_to_lower(str_sub(x,1,3))
x
```

####14.2.4 Locales  

```{r}
x = c("apple", "eggplant", "banana")
str_sort(x, locale = "en")
str_sort(x, locale = "haw")
```

####14.2.5 Exercises  
1. In code that doesn’t use stringr, you’ll often see paste() and paste0(). What’s the difference between the two functions? What stringr function are they equivalent to? How do the functions differ in their handling of NA?
